services:
  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=postgres://postgres:secret@database/postgres
    ports:
      - "3000:3000"

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

volumes:
  db-data: