services:
  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=postgres://postgres:secret@database/postgres
    ports:
      - "3020:3000"
  database:
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data